# Generated by Django 5.1.2 on 2024-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.TextField(default='https://i1.sndcdn.com/artworks-000188509722-d50ce4-t240x240.jpg')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
