# Generated by Django 5.1.2 on 2024-11-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0003_cliente_inversioncoleccion_metodopago_repartidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comfimada',
            field=models.BooleanField(default=0),
        ),
    ]
