# Generated by Django 5.1.2 on 2024-11-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0004_compra_comfimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plus.trabajador'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo_metodo_pago',
            field=models.CharField(max_length=20),
        ),
    ]
