# Generated by Django 5.1.2 on 2024-11-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0006_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='envio',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plus.repartidor'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tarifa_envio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='telefono',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
