# Generated by Django 5.1.2 on 2024-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0007_alter_envio_direccion_alter_envio_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
