# Generated by Django 5.1.2 on 2024-11-15 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0008_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
