# Generated by Django 5.1.2 on 2024-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0009_trabajador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
    ]
