# Generated by Django 5.1.2 on 2024-11-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0010_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='aceptada',
            field=models.BooleanField(default=0),
        ),
    ]
