# Generated by Django 5.1.2 on 2024-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0014_inversioncoleccion_confirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversioncoleccion',
            name='fecha_inversion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
