# Generated by Django 5.1.2 on 2024-11-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0015_alter_inversioncoleccion_fecha_inversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalias',
            name='fecha_regalia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
