# Generated by Django 5.1.2 on 2024-11-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0016_alter_regalias_fecha_regalia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devolucion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
