# Generated by Django 5.1.2 on 2024-11-27 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0017_alter_devolucion_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='compra',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plus.detallecompra'),
        ),
    ]
