# Generated by Django 5.0.3 on 2025-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0020_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante',
            field=models.ImageField(null=True, upload_to='comprobantes'),
        ),
    ]
