# Generated by Django 5.0.3 on 2025-03-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0021_alter_compra_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='devoluciones'),
        ),
    ]
